### ISSUE TITLE
more than just datum

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/more-than-just-datum#1]
Query in form and list

@muxlowc

**Comment by VanshitaGandhi** [comment]
Query in form and list

@mackenzierose

**Comment by muxlowc** [comment]
@VanshitaGandhi 

1) add img-flex to your logo img. and then add a max-width to your H1 (i've added a logo class to my h1)

.logo {
  max-width: 200px;
}

2) you'll want to add the relative class to your form, and a pin-lc to your label

```
<form class="relative" action="#">
        <label class="search-icon icon i-18 pin-lc" for="find" title="Search"><img src="images/search.svg" alt="Find"></label>
        <input class="search-input" type="search" id="find" required>
      </form>
```

3) for the table: I would add another div surrounding your Table tags

```
<div class="panel-data unit xs-1 s-1 m-2-3 l-3-4 island-1-2">
      <div class="table-wrapper scrollable">
        <table class="push-0">
```

and then for the css, add:

.table-wrapper table {
  min-width: 45em;
}

You can see I also added the class of "scrollable" which is I think a class from modulafier which allows that area to have a scroll to see overflown content

**Comment by VanshitaGandhi** [comment]
@hannahdelaney
